refactor: terminando o registro do formatador
DesignLiquido/vscode pull request #65
Opened 2024-06-14 20:59 UTC by Aristidescosta

Registro do formatador `mapler`

2024-06-14 21:01 UTC, leonelsanchesdasilva requested changes

2024-06-14 21:01 UTC, leonelsanchesdasilva commented on fontes/formatadores/portugol-studio-provedor-formatacao.ts
> -import * as vscode from 'vscode';
Qual o motivo de apagar isto?

2024-06-14 22:07 UTC, Aristidescosta commented on fontes/formatadores/portugol-studio-provedor-formatacao.ts
> -import * as vscode from 'vscode';
Acabei me esquecendo, havia apagado por teu feito alterações na main(principal) e quando alterei a branch não notei.

2024-07-21 18:01 UTC, leonelsanchesdasilva approved these changes

2024-07-21 18:01 UTC, merged